# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 596fd2dda4a8e05517afc21b4b85ef12c60066092ec469137ff1cf16127af46dd37c928ad905b1b5e0c09099194ff4813e63e4add423182b7b881793c314ae69

test:
  secret_key_base: 0eef789bf2127b0d9e019e9cdcb703f47b2f7c1dd011346c97e75a0d46f43fa74843564b7dd0dd643d3055fde3f89f83c8fa4c82d32567967ef5c137ac864f08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
